### PR TITLE
Api docs

### PR DESCRIPTION
**Pull request by kingsleyh**
This provides live API documentation for the node's REST API on the url: `http://testnet.sushichain.io:3000/docs/api/v1` 

it covers all the rest GET and POST at a basic level  - It can be refined in the future and also will add websocket pubsub documentation there in a different PR

Please review and merge if all good

### CODE REVIEW

**Comment by tbrand** [comment]
The documents seems almost good. But I found 2 issues.
- I always got `Network Error` when I try every APIs. - (1)
- I got many debug logs in my developer console. - (2)

For (1)


For (2)


Could you check them?

**Comment by kingsleyh** [comment]
Network error is because until this gets deployed there is no Cross Domain Origin headers on the API - but this PR adds them so will work after deploy or if you use localhost with this branch sushid running.

I’ll see why the console log comes - looks like it’s coming from an imported library - I think if I compile index.html in prod mode it will go away - I’ll fix

**Comment by tbrand** [comment]
Oh I see. I'll merge after the debug logs be disappeared.
Please ping me then.

**Comment by kingsleyh** [comment]
Fixed now - can be merged

**Comment by tbrand** [comment]
awesome!

**Pull request merged**
