### PR TITLE
Amounts with decimal places and adjust total supply amount

### PR DESCRIPTION
**Pull request by tbrand**
## Description

Finally I've finished the decimal places implementation.
This PR has include following changes

#### Client and API

- Client will use amounts with 8 decimal places to create unsigned transaction.
- API returns amounts with 8 decimal places. (e.g. `sushi wallet amount`, `sushi scars resolve`)
- API returns amounts in integer when it supplies pure transactions. (e.g. `/api/v1/blockchain`, `/api/v1/transaction/[id]`)

#### scaled column is added to transaction

We should carefully know that the transaction's amount is represented in decimal places or integer.
So I added `scaled` column to transaction to explicitly know the transaction's amounts are represented in decimal places or integer.

#### Fix the default token name

`SHARI` to `SUSHI`.

#### Total supply amounts

Adjust the total supply amounts to be about `20000000.00004112 [SUSHI]`.
Also I adjust the fees of each action.
- `0.0001` for basic usage (send tokens and third party dApps). (defined in UTXO and dApp)
- `0.001` for buying scars domain. `0.0001` for sell and cancel them.
- `0.1` for creating tokens.

## Related Issues

- https://github.com/SushiChain/SushiChain/issues/172
- https://github.com/SushiChain/SushiChain/issues/95

## Checklist
- [x] Fix specs
- [x] Every CI jobs finished successfully

## Note
**This change is totally breaking. So current blocks on testnet will be rejected from then.**
**So we have to announce before the deployment.**

### CODE REVIEW

**Comment by sdogruyol** [comment]
`100_000_000_000_700` = 100 trillion? Is that correct?

**Comment by kingsleyh** [comment]
yup that seems to be 100 trillion :)

**Comment by kingsleyh** [comment]
The circleci specs E2E failed - but I can't seem to restart the failed one - I think it's just intermittently unstable and when run again will pass - but I don't have enough permissions to restart it.

**Comment by kingsleyh** [comment]
@tbrand maybe you can get the E2E spec to pass and then merge it - and let me know and I will re-deploy

**Comment by kingsleyh** [comment]
a side effect of this is that after about 10 mins of mining my wallet looks like this:

```
  + -------------------- - -------------------- +
  |                token |               amount |
  | -------------------- | -------------------- |
  |                SHARI |             22567582 |
  + -------------------- - -------------------- +
```

I just mined over 22 million SHARI in a very short time. I guess it's relative because the total is 100 trillion. But seems a bit strange to me. It also means the fees seem way too low in comparison:

```
  + -------------------- - -------------------- +
  |               action |                  fee |
  | -------------------- | -------------------- |
  |                 send |                    1 |
  |            scars_buy |                  100 |
  |           scars_sell |                   10 |
  |         scars_cancel |                    1 |
  |         create_token |                 1000 |
  + -------------------- - -------------------- +
```

I'm gonna never need to ever mine more than half an hour - and I can pay for all kinds of actions for years to come lol !!!

**Comment by tbrand** [comment]
Yeah we should adjust  the fees then.

**Comment by tbrand** [comment]
@kingsleyh Additionally, as a breaking change, I moved `sign_r` and `sing_s` columns from transaction to senders.
So please deploy after merging https://github.com/SushiChain/SushiChain/pull/177.

**Comment by kingsleyh** [comment]
I fixed the specs but the E2E seem to be failing - I can’t re run them on circle - could you check and when they are passing do the merge and I will continue with the other PR

**Comment by tbrand** [comment]
got it

**Comment by tbrand** [comment]
Now all specs are fixed

**Pull request merged**
