### PR TITLE
Switch config

### PR DESCRIPTION
**Pull request by kingsleyh**
This provides the ability to have multiple configs and switch between them or disable / enable configuration.

```
sushi config save --testnet #defaults to name of config
sushi config save --testnet --name=c1
sushi config list # lists available configs
sushi config show # shows current config
sushi config show --name=c1 
sushi config use --name=c1 #switches to using this config
sushi config enable #enables config
sushi config disable #disables config
```

All config is stored in 1 yaml file - but it manipulates the data in the file

screen shot 2018-05-03 at 13 52 20

### CODE REVIEW

**Comment by kingsleyh** [comment]
hmm found an issue - fixing it

**Comment by kingsleyh** [comment]
All done now - you can review and merge when you have time

**Comment by tbrand** [comment]
OK. will see it

**Comment by tbrand** [comment]
@kingsleyh I've tried this then I got this error
```
> ./bin/sushi config save --mainnet
Error opening file '/Users/taichiro/.sushi/config' with mode 'r': No such file or directory
```

Why is this happend?

**Comment by kingsleyh** [comment]
hmm I will check

**Comment by kingsleyh** [comment]
Sorry made a mistake - have fixed it now.

**Pull request merged**
