### PR TITLE
Added REST APIs

### PR DESCRIPTION
**Pull request by tbrand**
## Issues
- https://github.com/SushiChain/SushiChain/issues/136
- https://github.com/SushiChain/SushiChain/issues/144

## Abstract
I've implemented REST APIsproposed.

In this Pull Request
- Some of API's pathes are modified for the consistency.
- "Pagination" implementation was skipped for now.
- Added Integration tests
- Define API response format

### CODE REVIEW

**Comment by tbrand** [comment]
@kingsleyh Could you review this?
All APIs are not documented yet but listed at here https://github.com/SushiChain/SushiChain/pull/150/files#diff-1218c025d5524cf7d10e0a52b51fae97R15

**Comment by kingsleyh** [comment]
Hi looks great so far here is my feedback:

1. All the GET requests on the API are great 
2. I think we should also add API calls for the scars domain (similar to how address is done)
3. you could save typing the rescue on every method with a closure (what you did is great) you might have noticed I like a closure :)

e.g

```
   private def with_response(context, &block)
     context.response.print api_success(yield)
     context
   rescue e : Exception
     rest_error(context, e)
   end

    def __v1_blockchain(context, params)
      with_response(context) { @blockchain.blockchain_info.blockchain_impl(false) }
    end

  def __v1_block_index_header(context, params)
      with_response(context) do
        index = params["index"].to_i64
        @blockchain.blockchain_info.block_impl(true, index)
      end
    end
```

4. Looking forward to seeing the POST request for transaction creating - the wallet can use this
5. Also looking forward to seeing pagination - this is important for the wallet to show transactions
6. I would also like a websocket for when a new block is pushed 
7. I think I would like some other websockets but maybe do those in a different issue

**Comment by tbrand** [comment]
Thanks for the review!
For 2, 3. OK I'll fix them.
For 4 ~ 7. I'll do in **other PRs**.

**Comment by kingsleyh** [comment]
Awesome :)

**Comment by kingsleyh** [comment]
Where can we put the documentation? Html and JavaScript page so we can have docs and the tester - if you could make one html page I could do the rest - could just say hello world and I can add the rest

**Comment by tbrand** [comment]
@kingsleyh I've fixed and added scars for GET request.

Let me confirm that
1. pagination, websocket and post for REST will be other Pull Requests.
2. html page will be other Pull Request. (I this StaticFileHandler will help. https://crystal-lang.org/api/0.24.2/HTTP/StaticFileHandler.html)

**Comment by kingsleyh** [comment]
Looks great :)

But could we add a GET for  wallet via domain:

```
sushi wallet amount --domain=bararchy.sc -n http://localhost:3000
```

maybe

```
v1/domain/{:domain}/unconfirmed
```
 or something like that

**Comment by tbrand** [comment]
@kingsleyh Added

**Comment by kingsleyh** [comment]
Looks great - I will merge when the tests finish

**Pull request merged**
