### PR TITLE
Bintray publish

### PR DESCRIPTION
**Pull request by raymanoz**
## Description
This uses the circleci build to create a version of the application by writing the version from `shard.yml`, and the `CIRCLE_BUILD_NUM`. It then packages up the minimal source code so that brew (down the line) will be able to pull this code, build it locally, and install it.

## Related Issues
- https://github.com/SushiChain/SushiChain/issues/320
- https://github.com/SushiChain/SushiChain/issues/328

## Checklist
- [ ] Every CI jobs finished successfully

### CODE REVIEW

**Comment by kingsleyh** [comment]
some questions:

1. Do we need to include `e2e` in this? https://github.com/SushiChain/SushiChain/blob/d411b42865fd0ab721f2c6f7775fdd36720d337d/publish/bintray.sh#L8

2. When you start up a node it looks for the api directory on a relative path to show the api UI - so we should probably take that also and get brew to put it somewhere during the install that the sushid binary can find. Or we can so something better here - there is also a related issue to evaluate moving to the swagger OpenAPI doc for the api docs.

3. Currently it doesn't look like the version.txt is being updated at the right time. Unless I missed it - it seems like there is no call to `shards build --release` after updating the version.txt - and it's during this build that the version.txt will be consumed.

**Comment by raymanoz** [comment]
1. I only included e2e because it seems to get built when you do a `shards build --release`
2. I'll look into this as I do the brew script
3. look in `.circleci/config.yml`. The `publish-bintray` step first writes the version into `version.txt`, then packages everything up and pushes the source to bintray. The idea is that with the version having been set by the build server here, when later brew downloads the source from bintray, the version number will already be set.

**Comment by kingsleyh** [comment]
Ok - cool - in that case we should not distribute e2e - so you can remove it 

Ah yes - the plan is to package the files and then compile on the target system - like a Mac via brew - ok now the question about whether a clear text version makes sense - but it’s still fine in clear text

**Comment by kingsleyh** [comment]
Btw - you can chose to run on a circleci Mac instance - in the circleci config

**Comment by raymanoz** [comment]
Why would I run a Mac instance? Are you suggesting we could build a binary in circle, for distribution to Macs via brew?

**Comment by raymanoz** [comment]
`e2e` removed

**Comment by kingsleyh** [comment]
yeah - but not sure if that costs money to use other OS's - anyway lets go with your current approach.

**Pull request merged**
